name: asbear
version: '3.0'
grade: 'stable'
base: core20

license: GPL-3.0
icon: 'release/data/gui/logo.png'

summary: 'A simple, but efficient audio recorder with an embedded player and a converter'
description: |
    Another Simple But Efficient Audio Recorder (ASBEAR) is basically an audio recorder.
    
    It currently allows you to use three codecs : raw PCM (WAV), FLAC and Vorbis (OGG).
    You can easily convert your recordings between these three codecs and manage them directly from the application : rename, move, remove...
    
    There is only two languages for the UI : English and French, and I do not plan on adding more.
    And obviously, there is a dark theme !


contact: ['nyanmaths@protonmail.com', 'https://memetech.weebly.com/contact']
website: 'https://memetech.weebly.com'
issues: ['https://github.com/NyanMaths/ASBEAR/issues', 'https://memetech.weebly.com/MRecorder']
source-code: 'https://github.com/NyanMaths/ASBEAR'


confinement: strict

apps:
    asbear:
        command: bin/asbear
        desktop: 'asbear.desktop'

parts:
    asbear:
        plugin: qmake
        qt-version: qt5
        source: https://github.com/NyanMaths/ASBEAR
        build-packages:
         - libsfml-dev


plugs:
    asbear-removable-media:
        interface: removable-media
    asbear-audio-playback:
        interface: audio-playback
    asbear-audio-record:
        interface: audio-record
