name: asbear
version: 3.0
grade: dev
base: core20


issues: ['https://github.com/NyanMaths/ASBEAR/issues', 'https://memetech.weebly.com/MRecorder']
source-code: ['https://github.com/NyanMaths/ASBEAR']


confinement: strict

apps:
    asbear:
        command: asbear
        desktop: 'ASBEAR.desktop'

parts:
    asbear:
        source: 'snap'

plugs:
    asbear-removable-media:
        interface: removable-media
    asbear-audio-playback:
        interface: audio-playback
    asbear-audio-record:
        interface: audio-record
